/**
 * Portfolio company names — auto-generated from holdings CSV.
 * Used by deal detector to prevent auto-creating deals for existing portfolio companies.
 * These are normalized lowercase names. Match by checking if extracted company name
 * (lowercase, stripped of Inc/Corp/LLC) is in this set.
 *
 * Generated: 2026-02-27 from holdings_consolidated_2026-02-27.csv
 * Source: 288 unique holdings → 654 normalized name variants
 */
export const PORTFOLIO_NAMES = new Set([
  '8090',
  '8090 solutions',
  '8090 solutions inc',
  'addepar',
  'addepar, inc.',
  'affirm holdings',
  'agentio',
  'agentio inc.',
  'agentsync',
  'agentsync, inc.',
  'airbase',
  'airbase inc.',
  'alka',
  'alka inc.',
  'allen control systems',
  'allen control systems inc.',
  'anduril industries',
  'anduril industries, inc.',
  'anvil foundry',
  'anvil foundry, inc.',
  'apollo club',
  'apollo club nabv',
  'arch labs',
  'arch labs inc.',
  'arcol technology',
  'arcol technology, inc.',
  'arist',
  'arist holdings',
  'arist holdings inc.',
  'arovy',
  'arovy, inc.',
  'astrodon corporation',
  'astrodonoration',
  'athena formation',
  'athena formation, inc.',
  'attuned',
  'attuned corp',
  'autopilot holdings corporation (fka iris social stock app, inc.)',
  'autopilot holdingsoration',
  'badge',
  'badge group',
  'badge group, inc.',
  'bbot',
  'bbot, inc.',
  'bird global',
  'bird rides',
  'bird rides, inc./bird global,inc.',
  'bird rides/bird global',
  'bitgo',
  'bitgo holdings',
  'bitgo holdings, inc.',
  'bitwise asset management',
  'bitwise asset management, inc.',
  'bottomless',
  'bottomless, inc.',
  'brud',
  'brud inc./dapper labs, inc.',
  'brud/dapper labs',
  'buck labs',
  'buck labs, inc. (fka receivable ai)',
  'cabal',
  'cabal inc.',
  'cafe x',
  'cafe x technologies',
  'cafe x technologies, inc.',
  'cartwheel',
  'cartwheel inc.',
  'catamorphic co.',
  'cedar cares',
  'cedar cares, inc.',
  'champ sports',
  'champ sports company',
  'chia network',
  'chia network inc.',
  'clickup',
  'clickup inc.',
  'city storage systems',
  'city storage systems llc',
  'cloud',
  'cloud technologies',
  'cloud technologies, inc.',
  'cloud9 esports',
  'cloud9 esports, inc.',
  'coffey ventures',
  'coffey ventures, inc.',
  'coinzinga',
  'coinzinga inc.',
  'complyant app',
  'complyant app, inc.',
  'compose ai',
  'compose ai, inc.',
  'console',
  'console corp.',
  'conversenow',
  'conversenow technologies',
  'conversenow technologies, inc.',
  'coparse',
  'coparse, inc.',
  'copyai',
  'copyai inc./rali, inc.',
  'copyai/rali',
  'cortex applications',
  'cortex applications inc.',
  'created by humans',
  'created by humans, inc.',
  'crewai',
  'crewai, inc.',
  'crypto losses',
  'culture',
  'culture biosciences',
  'culture biosciences, inc.',
  'cure',
  'cure group',
  'cure group gmbh',
  'cv investments',
  'cv investments, llc',
  'dapper labs',
  'dapper labs, inc.',
  'datasembly',
  'datasembly, inc.',
  'daylight',
  'daylight security',
  'daylight security, inc.',
  'dayton craft i(swarm)',
  'dayton craft i, llc (swarm)',
  'dayton craft ii(loft dynamics; fka vrmotion ag))',
  'dayton craft ii, llc (loft dynamics; fka vrmotion ag))',
  'dayton craft iii(xona space systems)',
  'dayton craft iii, llc (xona space systems)',
  'delta gamma bravo',
  'delta gamma bravo holdings',
  'delta gamma bravo holdings, llc',
  'dexx',
  'dexx technologies',
  'dexx technologies inc.',
  'digitalbrain',
  'digitalbrain, inc.',
  'ditto tech',
  'ditto tech inc.',
  'docasaurus',
  'docasaurus, inc.',
  'dock labs',
  'dock labs, inc.',
  'dray',
  'dray holdings',
  'dray holdings corp.',
  'dydx',
  'dydx (dydx)',
  'dydx trading',
  'dydx trading inc.',
  'echomark',
  'echomark, inc.',
  'eight sleep',
  'eight sleep inc.',
  'elliot',
  'elliot technologies',
  'elliot technologies, inc.',
  'endeavorai',
  'endeavorai (fka industrial.ai)',
  'entera',
  'entera holdings',
  'entera holdings, inc.',
  'equals',
  'equals technologies',
  'equals technologies, inc.',
  'fellow insights',
  'fellow insights inc.',
  'find solace',
  'find solace, inc.',
  'fingerprintjs',
  'fingerprintjs, inc.',
  'finpeak',
  'finpeak, inc.',
  'firestorm labs',
  'firestorm labs, inc.',
  'first resonance',
  'first resonance, inc.',
  'fold',
  'fold holdings',
  'fold, inc./fold holdings, inc.',
  'fold/fold',
  'fold/fold holdings',
  'frigade',
  'frigade, inc.',
  'galoy',
  'galoy inc.',
  'garden retirement',
  'garden retirement company',
  'garuda labs',
  'garuda labs, inc.',
  'genhealth',
  'genhealth inc.',
  'gero labs',
  'gero labs, inc.',
  'giggl',
  'giggl, inc.',
  'glean',
  'glean technologies',
  'glean technologies, inc.',
  'glide labs',
  'glide labs, inc.',
  'glue groups',
  'glue groups inc.',
  'goody',
  'goody technologies',
  'goody technologies, inc.',
  'grata',
  'grata inc.',
  'greenlite',
  'greenlite technologies',
  'greenlite technologies, inc.',
  'groq',
  'groq, inc.',
  'grow platform',
  'grow platform inc.',
  'haight & ashbury',
  'haight & ashbury corp.',
  'hallway',
  'hallway technologies',
  'hallway technologies, inc.',
  'handoffs',
  'handoffs inc.',
  'harmonic ai',
  'harmonic ai, inc.',
  'headgum',
  'headgum inc.',
  'herohq',
  'herohq, inc.',
  'highlight',
  'highlight inc./catamorphic co.',
  'highlight/catamorphic co.',
  'hivemapper',
  'hivemapper, inc.',
  'homebound',
  'homebound technologies',
  'homebound technologies, inc.',
  'horizon 3 ai',
  'horizon 3 ai, inc.',
  'hotswap corporation',
  'hotswaporation',
  'humen',
  'humen, inc.',
  'hyfix spatial intelligence incorporated',
  'hyfix spatial intelligenceorporated',
  'hypertools',
  'hypertools, inc.',
  'index labs',
  'index labs, inc.',
  'inertia',
  'inertia enterprises',
  'inertia enterprises inc.',
  'infinilake',
  'infinilake inc.',
  'inspira education',
  'inspira education group',
  'inspira education group, inc.',
  'integrated cinematics',
  'integrated cinematics inc.',
  'ise ai',
  'jetstream',
  'jetstream security',
  'jetstream security, inc.',
  'jumpstart filings',
  'jumpstart filings inc.',
  'juniper',
  'juniper solutions',
  'juniper solutions, inc.',
  'kaz',
  'kaz inc.',
  'keyto',
  'keyto, inc.',
  'kitchen stadium',
  'kitchen stadium inc.',
  'klue labs',
  'klue labs, inc.',
  'knock labs',
  'knock labs, inc.',
  'komment ai',
  'komment ai inc',
  'koyfin',
  'koyfin inc.',
  'kresus labs',
  'kresus labs, inc.',
  'latch',
  'latch, inc.',
  'laudable',
  'laudable, inc.',
  'life school labs',
  'life school labs, inc.',
  'lightning labs',
  'lightning labs, inc.',
  'liquidity financial',
  'liquidity financial, inc./signify holdings, inc.',
  'liquidity financial/signify',
  'liquidity financial/signify holdings',
  'lnd work',
  'lnd work, inc.',
  'locals technology',
  'locals technology, inc./rumble, inc.',
  'locals technology/rumble',
  'loft dynamics; fka vrmotion ag',
  'logseq',
  'logseq, inc.',
  'lolli',
  'lolli, inc.',
  'madeira',
  'madeira security',
  'madeira security, inc.',
  'mango',
  'mango technologies',
  'mango technologies, inc.',
  'marketplace capital',
  'marketplace capital, lp',
  'masad capital, lp - a4',
  'masad capital- a4',
  'meez culinary',
  'meez culinary solutions',
  'meez culinary solutions, inc.',
  'metamap',
  'metamap, inc./incode technologies, inc.',
  'metamap/ode',
  'metamap/ode technologies',
  'minehub technologies',
  'minerva knows',
  'minerva knows, inc.',
  'mistro',
  'mistro inc',
  'modyfi',
  'modyfi, inc.',
  'moesif',
  'moesif, inc.',
  'moksha ventures',
  'moksha ventures, llc',
  'moreno loan (route)',
  'mote',
  'mote technologies',
  'mote technologies, inc.',
  'mozart data',
  'mozart data, inc.',
  'mtp capital',
  'multicoin',
  'neo',
  'neo security',
  'neo security, inc.',
  'neuralink',
  'neuralink corp.',
  'nexthop systems',
  'nexthop systems, inc.',
  'neyborly',
  'neyborly, inc.',
  'nightingale intelligent systems',
  'nightingale intelligent systems, inc.',
  'nomos ai',
  'nomos ai, inc.',
  'nomzplz',
  'nomzplz inc.',
  'northspyre',
  'northspyre inc.',
  'not just snacks',
  'not just snacks inc.',
  'ockam',
  'ockam inc.',
  'octave',
  'octave technologies',
  'octave technologies, inc.',
  'ode technologies',
  'ohalo',
  'ohalo genetics',
  'ohalo genetics, inc.',
  'okay health',
  'okay health inc.',
  'okendo',
  'okendo pty ltd',
  'openevidence',
  'openevidence, inc.',
  'openphone',
  'openphone technologies',
  'openphone technologies, inc.',
  'orum',
  'orum inc.',
  'oscar',
  'oscar technologies',
  'oscar technologies, inc.',
  'overflow app',
  'overflow app inc.',
  'pair team',
  'pair team, inc.',
  'pando hr',
  'pando hr inc.',
  'paradedb',
  'paradedb, inc.',
  'paramount skydance',
  'partnerbeat',
  'partnerbeat, inc.',
  'passes',
  'passes, inc.',
  'pearl',
  'pearl inc.',
  'people data labs',
  'people data labs inc.',
  'peregrine',
  'peregrine technologies',
  'peregrine technologies, inc.',
  'pickle poll',
  'pickle poll, inc.',
  'pipe',
  'pipe technologies',
  'pipe technologies inc.',
  'plant identification',
  'plant identification, inc.',
  'playbit',
  'playbit inc.',
  'plume health',
  'plume health, inc.',
  'pocketlist',
  'pocketlist inc.',
  'polarity ln',
  'polarity ln, inc.',
  'potential energy labs',
  'potential energy labs, inc./rali, inc.',
  'potential energy labs/rali',
  'primer labs',
  'primer labs inc.',
  'productboard',
  'productboard, inc.',
  'purpleair',
  'purpleair, inc.',
  'ragie',
  'rali',
  'rare bits',
  'rare bits, inc.',
  'real estate digital',
  'real estate digital technologies',
  'real estate digital technologies corp.',
  'realcast',
  'realcast inc.',
  'realize',
  'realize, inc.',
  'reddit',
  'reddit, inc.',
  'reflect software',
  'reflect software, inc.',
  'replit',
  'replit, inc.',
  'resemble ai',
  'resemble ai, inc.',
  'reset button',
  'respell',
  'respell, inc.',
  'returnly technologies',
  'returnly technologies, inc./affirm holdings, inc.',
  'returnly technologies/affirm',
  'returnly technologies/affirm holdings',
  'reviso',
  'reviso, inc.',
  'rewindlive',
  'rewindlive, inc.',
  'river financial',
  'river financial, inc.',
  'roboflow',
  'roboflow, inc.',
  'rocketvisor corporation',
  'rocketvisororation',
  'route',
  'route app',
  'route app, inc.',
  'rumble',
  'rumble, inc.',
  'rumi.ai',
  'rumi.ai, inc.',
  'runaway media',
  'runaway media, inc./paramount skydance',
  'runaway media/paramount skydance',
  'saasgrid',
  'saasgrid, inc.',
  'salesroom',
  'salesroom, inc.',
  'salted',
  'salted inc.',
  'samepage',
  'samepage, inc.',
  'sandbox vr',
  'sandbox vr, inc.',
  'sandwith ventures',
  'sandwith ventures, lp',
  'saronic',
  'saronic technologies',
  'saronic technologies, inc.',
  'sbar endurance',
  'sbar endurance, inc.',
  'scenery',
  'scenery corp.',
  'schumpeter',
  'schumpeter enterprises',
  'schumpeter enterprises, inc.',
  'scope',
  'scope enterprises',
  'scope enterprises, inc.',
  'scope3',
  'scope3, pbc',
  'scout funds',
  'scratchpad',
  'scratchpad, inc.',
  'seated',
  'seated technologies',
  'seated technologies, inc.',
  'secoda',
  'secoda inc.',
  'securitypal',
  'securitypal, inc.',
  'sender',
  'sender, inc.',
  'sensible',
  'sensible technologies',
  'sensible technologies inc.',
  'sentilink',
  'sentilink corp.',
  'sequin labs',
  'sequin labs, inc.',
  'shef',
  'shef, inc.',
  'shelfflip',
  'shelfflip, inc.',
  'sidekick data',
  'sidekick data,inc. (fka avenue 8)',
  'signify holdings',
  'simplelab',
  'simplelab, inc.',
  'simplify jobs',
  'simplify jobs, inc.',
  'sofar ocean',
  'sofar ocean technologies',
  'sofar ocean technologies, inc.',
  'soundstripe',
  'soundstripe inc.',
  'sourcegraph',
  'sourcegraph, inc.',
  'space exploration',
  'space exploration technologies',
  'space exploration technologies corp.',
  'spekit',
  'spekit inc.',
  'spellbound labs',
  'spellbound labs, inc.',
  'square roots urban growers',
  'square roots urban growers, inc.',
  'starbridge.ai',
  'starbridge.ai, inc.',
  'stationfy',
  'stationfy inc.',
  'streetfair',
  'streetfair holdings',
  'streetfair holdings inc.',
  'substrate labs',
  'substrate labs inc.',
  'suger',
  'suger inc.',
  'supabase',
  'supabase, inc.',
  'superplastic',
  'superplastic, inc.',
  'swarm',
  'taggle software',
  'taggle software inc',
  'tbc - the boring',
  'tbc - the boring company',
  'tdm',
  'tdm inc.',
  'teller',
  'teller, inc.',
  'ten key labs incorporated',
  'ten key labsorporated',
  'terminal',
  'terminal, inc.',
  'textline',
  'textline holdings',
  'textline, inc./textline holdings, llc',
  'textline/textline',
  'textline/textline holdings',
  'the abstract operations',
  'the abstract operations company',
  'the june care',
  'the june care company',
  'the june care company inc.',
  'thndr',
  'thndr ltd',
  'til',
  'til technologies',
  'til technologies inc.',
  'tldr',
  'tldr technologies',
  'tldr technologies, inc.',
  'tomo hq',
  'tomo hq, inc.',
  'toothio',
  'toothio, inc.',
  'trellis research',
  'trellis research, inc.',
  'trove information',
  'trove information technologies',
  'trove information technologies, inc.',
  'trusted',
  'trusted, inc.',
  'trustlayer',
  'trustlayer inc.',
  'trynow',
  'trynow, inc.',
  'two front',
  'two front corp.',
  'unframe',
  'unframe, inc.',
  'upwind',
  'upwind security',
  'upwind security, inc.',
  'userback',
  'userback holdings',
  'userback holdings pty ltd',
  'vangoux',
  'vangoux inc.',
  'vanta',
  'vanta inc',
  'vendr',
  'vendr, inc.',
  'verifiable',
  'verifiable inc.',
  'viable fit',
  'viable fit, inc.',
  'voiceflow',
  'voiceflow, inc.',
  'voltage incorporated',
  'voltageorporated',
  'vooma',
  'vooma inc.',
  'walker',
  'walker/moreno loan (route)',
  'waybridge technologies',
  'waybridge technologies inc./minehub technologies, inc.',
  'waybridge technologies/minehub',
  'waybridge technologies/minehub technologies',
  'whoosh',
  'whoosh, inc.',
  'woflow',
  'woflow inc.',
  'worklife ventures ii',
  'worklife ventures ii, lp',
  'workos',
  'workos, inc.',
  'workwise',
  'workwise solutions',
  'workwise solutions inc.',
  'x.ai',
  'x.ai corp.',
  'x1 inc.',
  'xona space systems',
  'zipper',
  'zipper, inc.',
])

/**
 * Check if a company name matches a portfolio company.
 * Normalizes the input by stripping Inc/Corp/LLC/etc and lowercasing.
 */
export function isPortfolioCompanyName(name: string): boolean {
  const lower = name.toLowerCase().trim()
  if (PORTFOLIO_NAMES.has(lower)) return true

  // Strip common suffixes
  const normalized = lower
    .replace(/,?\s*(inc\.?|corp\.?|llc|ltd\.?|pbc|pty|gmbh|holdings?|technologies?|solutions?|group|company|enterprises?|incorporated|security|labs?)\s*/gi, '')
    .replace(/\s+/g, ' ')
    .trim()
  if (PORTFOLIO_NAMES.has(normalized)) return true

  // Try without trailing AI/App/HQ
  const shorter = normalized.replace(/\s+(ai|app|hq)$/i, '').trim()
  if (shorter !== normalized && PORTFOLIO_NAMES.has(shorter)) return true

  return false
}
